<a href="https://colab.research.google.com/github/OjashShakya/Ojash_Shakya_2408654_AI_Workshops/blob/main/Ojash_Shakya_2408654_Workshop_W1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Ojash Shakya

ID: 2408654

##TO - DO - Task

Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

emptyArray = np.zeros((2, 2))
print("Empty array (2x2) filled with zeros:\n", emptyArray)

Empty array (2x2) filled with zeros:
 [[0. 0.]
 [0. 0.]]


2. Initialize an all one array with size 4X2.

In [ ]:
oncesArray = np.ones((4, 2))
print("All ones array (4x2):\n", oncesArray)

All ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
fillArray = np.full((3, 3), 7)
print("Array filled with 7 (3x3):\n", fillArray)

Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
givenArray = np.array([[1, 2, 3], [4, 5, 6]])
emptyArray = np.zeros_like(givenArray)
print("Zeros array with same shape as given array:\n", emptyArray)

Zeros array with same shape as given array:
 [[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}


In [ ]:
ones_like_array = np.ones_like(given_array)
print("Ones array with same shape as given array:\n", ones_like_array)

Ones array with same shape as given array:
 [[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Numpy array from list:\n", numpy_array)

Numpy array from list:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
array_10_49 = np.arange(10, 50)
print("Array from 10 to 49:\n", array_10_49)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print("3x3 matrix:\n", matrix_3x3)

3x3 matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?