<a href="https://colab.research.google.com/github/OjashShakya/Ojash_Shakya_2408654_AI_Workshops/blob/main/Ojash_Shakya_2408654_Workshop_W1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Ojash Shakya

ID: 2408654

##TO - DO - Task

Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.

In [6]:
import numpy as np

emptyArray = np.zeros((2, 2))
print(emptyArray)

[[0. 0.]
 [0. 0.]]


2. Initialize an all one array with size 4X2.

In [2]:
oncesArray = np.ones((4, 2))
print(oncesArray)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [5]:
fillArray = np.full((2, 3), 4)
print(fillArray)

[[4 4 4]
 [4 4 4]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [6]:
sampleArray = np.array([[1, 2, 3], [4, 5, 6]])
newArray = np.zeros_like(sampleArray)
print(newArray)

[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}


In [9]:
sampleArray = np.array([[1, 2, 3], [4, 5, 6]])
newArray = np.ones_like(sampleArray)
print(newArray)

[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [10]:
new_list = [1, 2, 3, 4]
numpyArray = np.array(new_list)
print(numpyArray)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [11]:
arrayRange = np.arange(10, 50)
print(arrayRange)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [12]:
arrayMatrix = np.arange(0, 9).reshape(3, 3)
print(arrayMatrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [14]:
indentityMatrix = np.eye(3)
print(indentityMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}


In [17]:
randomArray = np.random.random(30)
mean = randomArray.mean()
print(randomArray)
print("Mean: ", mean)

[0.08891948 0.01155932 0.52018782 0.51488596 0.69528421 0.45627514
 0.42720661 0.34401951 0.36764997 0.7257646  0.04681978 0.71837785
 0.14211965 0.75203536 0.29078469 0.57686195 0.49900242 0.7250378
 0.35104402 0.75135959 0.74823351 0.07838031 0.29159124 0.06131009
 0.26072862 0.81097789 0.42002321 0.49217635 0.3471863  0.34052602]
Mean:  0.4285443095733265


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [20]:
randomArray = np.random.random((10, 10))
min_value = randomArray.min();
max_value = randomArray.max();
print(randomArray);
print("\nRandom Matrix Min:", min_value, "Max:", max_value);

[[7.27466985e-01 9.61113393e-01 6.23435280e-01 9.46899029e-01
  5.99913706e-02 8.34889843e-01 3.48231824e-02 6.05318086e-01
  5.22642131e-01 3.95153633e-02]
 [9.75227993e-01 3.21070648e-01 5.07551113e-01 1.97697509e-01
  8.47561480e-02 1.19737419e-01 8.30472582e-01 3.21998985e-01
  2.77956902e-01 4.39843006e-04]
 [7.31224852e-01 5.62860520e-01 7.18293393e-01 6.00890496e-01
  7.73974471e-01 1.27543876e-02 4.67041051e-02 7.41019271e-02
  3.22326333e-01 2.29024224e-01]
 [1.35910062e-01 1.76510634e-01 8.34943332e-01 5.95521882e-01
  1.59671437e-01 4.17646022e-01 8.52255773e-01 7.18782309e-01
  6.48249907e-01 3.04054927e-01]
 [6.06365046e-02 1.43806238e-01 1.83005683e-01 9.18832293e-01
  3.96735014e-01 9.53253057e-01 9.34080314e-01 7.14331972e-01
  7.93654987e-01 5.54624822e-01]
 [5.98781187e-01 4.93735389e-01 9.58913569e-01 3.68414423e-02
  1.19862797e-01 3.92109488e-01 8.90362654e-01 5.56269095e-01
  8.62969554e-01 9.64961046e-02]
 [3.14265713e-01 7.00347655e-01 5.02004487e-01 7.57136740e

6. Create a zero array of size 10 and replace 5th element with 1.


In [22]:
zeroArray = np.zeros(10)
zeroArray[0] = 1
print(zeroArray)

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].


In [23]:
arr = [1, 2, 0, 0, 4, 0]
reverseArray = arr[::-1]
print(reverseArray)

[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.


In [27]:
arr = np.ones((3,4))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [29]:
checkerArray = np.zeros((8, 8))
checkerArray[1::2, ::2] = 1
checkerArray[::2, 1::2] = 1
print(checkerArray)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.


In [30]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [32]:
print(x + y)

[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [33]:
print(x - y)

[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.


In [34]:
print(x * 4)

[[ 4  8]
 [12 20]]


4. Find the square of each element of the array.


In [35]:
print(x**2)

[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.


In [40]:
print("v.w:\n", np.dot(v, w))
print("x.v:\n", np.dot(x, v))
print("x.y:\n", np.dot(x, y))

v.w:
 219
x.v:
 [29 77]
x.y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.}

In [45]:
print("Concatenate x and y along rows:\n", np.concatenate((x, y)))
print("Concatenate v and w along columns:\n", np.vstack((v, w)))

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [46]:
try:
    np.concatenate((x, v))
except ValueError as e:
    print("\nError in Concatenation of x and v:\n", e)


Error in Concatenation of x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.




In [7]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

In [54]:
inverseOfA = np.linalg.inv(A)
I = np.dot(A, inverseOfA)
print("\nA.A^-1:\n", I)


A.A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.


In [9]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


3. Prove (AB)T = BTAT

In [10]:
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))

print("(AB)^T:\n", AB_T)
print("B^T.A^T:\n", BT_AT)

(AB)^T:
 [[23 51]
 [13 29]]
B^T.A^T:
 [[23 51]
 [13 29]]


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}


In [11]:
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])
inverseOfA = np.linalg.inv(A)
# X = A^-1.B
X = np.dot(inverseOfA, B)

print("(x,y,z) = ", X)

(x,y,z) =  [ 2.  1. -2.]
